---
spring:
  profiles: dev

server:
  port: 8081

# 对象
person:
  name: zhangsan
  age: 20
  address:
    - beijing
    - shanghai

##行内写法
person2: {name: zhangsan,age: 20}

# 数组
address:
  - beijing
  - shanghai

## 行内写法
address2: [beijing,shanghai]

# 纯量
msg1: 'hello \n world' # 不识别转义字符，会原样输出
msg2: "hello \n world" # 会识别转移字符

# 参数引用
name: lisi
age: 10

person1:
  name: ${name}
---
spring:
  profiles: test

server:
  port: 8082

# 对象
person:
  name: zhangsan
  age: 20
  address:
    - beijing
    - shanghai

##行内写法
person2: {name: zhangsan,age: 20}

# 数组
address:
  - beijing
  - shanghai

## 行内写法
address2: [beijing,shanghai]

# 纯量
msg1: 'hello \n world' # 不识别转义字符，会原样输出
msg2: "hello \n world" # 会识别转移字符

# 参数引用
name: lisi
age: 10

person1:
  name: ${name}
---
spring:
  profiles: pro

server:
  port: 8083

# 对象
person:
  name: zhangsan
  age: 20
  address:
    - beijing
    - shanghai

##行内写法
person2: {name: zhangsan,age: 20}

# 数组
address:
  - beijing
  - shanghai

## 行内写法
address2: [beijing,shanghai]

# 纯量
msg1: 'hello \n world' # 不识别转义字符，会原样输出
msg2: "hello \n world" # 会识别转移字符

# 参数引用
name: lisi
age: 10

person1:
  name: ${name}
---
spring:
  profiles:
    active: dev